[package]
name = "versequest-be"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-runtime = "0.17.0"
shuttle-axum = "0.17.0"
shuttle-secrets = "0.17"
axum = "0.6.18"
tokio = "1.28.1"
anyhow = "1.0.71"
serde = "1.0"